### ISSUE TITLE
Configuration and metafile issues

### ISSUE THREAD

**Issue by vertxxyz** [LotteMakesStuff/Facepunch.Steamworks#1]
Hi Lotte! One minor issue and one major:

1. There are a couple of meta files in the unity plugin that don't have associated files, as the `*.pdb` is ignored, but their associated `*.pdb.meta` isn't. https://github.com/LotteMakesStuff/Facepunch.Steamworks/tree/master/UnityPlugin Same deal with `.xml.meta`.
2. Due to a Unity bug, the `Facepunch.Steamworks.Win64` metafile is broken in such a way that it appears to be correctly configured to exclude mac, but in reality it has it included. This causes mac builds to fail.

### 2. Expanded
https://github.com/LotteMakesStuff/Facepunch.Steamworks/blob/master/UnityPlugin/Facepunch.Steamworks.Win64.dll.meta
Note the sections:
https://github.com/LotteMakesStuff/Facepunch.Steamworks/blob/006aa35d38c31a6301c597bc819b6d3eb3991a6b/UnityPlugin/Facepunch.Steamworks.Win64.dll.meta#L16-L30

(Exclude Win64 and Exclude OSXUniversal shouldn't have the same values)

https://github.com/LotteMakesStuff/Facepunch.Steamworks/blob/006aa35d38c31a6301c597bc819b6d3eb3991a6b/UnityPlugin/Facepunch.Steamworks.Win64.dll.meta#L89-L92

Deleting the metafile and setting it up again fixed the issue on my end.

An example of what it ended up as, where the values appear to make sense:

```yaml
fileFormatVersion: 2
guid: b3ad7ccc15f481747842885a21b7b4ab
PluginImporter:
  externalObjects: {}
  serializedVersion: 2
  iconMap: {}
  executionOrder: {}
  defineConstraints: []
  isPreloaded: 0
  isOverridable: 1
  isExplicitlyReferenced: 0
  validateReferences: 1
  platformData:
  - first:
      : Any
    second:
      enabled: 0
      settings:
        Exclude Editor: 0
        Exclude Linux64: 1
        Exclude OSXUniversal: 1
        Exclude Win: 1
        Exclude Win64: 0
  - first:
      Any: 
    second:
      enabled: 1
      settings: {}
  - first:
      Editor: Editor
    second:
      enabled: 1
      settings:
        CPU: x86_64
        DefaultValueInitialized: true
        OS: Windows
  - first:
      Standalone: Linux64
    second:
      enabled: 0
      settings:
        CPU: None
  - first:
      Standalone: OSXUniversal
    second:
      enabled: 0
      settings:
        CPU: None
  - first:
      Standalone: Win
    second:
      enabled: 0
      settings:
        CPU: None
  - first:
      Standalone: Win64
    second:
      enabled: 1
      settings:
        CPU: AnyCPU
  - first:
      Windows Store Apps: WindowsStoreApps
    second:
      enabled: 0
      settings:
        CPU: AnyCPU
  userData: 
  assetBundleName: 
  assetBundleVariant: 
```
